src/SiteBundle/Entity/Offre.php
<?php

namespace SiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use SiteBundle\Entity\Session;

/**
 * Offre
 *
 * @ORM\Table(name="offre")
 * @ORM\Entity(repositoryClass="SiteBundle\Repository\OffreRepository")
 */
class Offre
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="DateDepot", type="date")
     */
    private $dateDepot;


    /**
     * @var string
     *
     * @ORM\Column(name="etat_offre", type="string", columnDefinition="enum('En attente de validation','En ligne','Pourvue','En attente de modification','Refuser')" ,nullable=true , options={"default":"0"})
     */
    private $etatOffre;


    /**
     * @var string
     *
     * @ORM\Column(name="licence_concerne",type="string", columnDefinition="enum('METINET', 'IEM')",nullable=true)
     */
    private $licenceConcerne;

    /**
     * @var string
     *
     * @ORM\Column(name="Sujet", type="text",nullable=true)
     */
    private $sujet;

    /**
     * @var string
     *
     * @ORM\Column(name="Titre", type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\Entreprise")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Entreprise;

    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\MAP")
     * @ORM\JoinColumn(nullable=false)
     */
    private $MAP;

    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\Etudiant")
     * @ORM\JoinColumn(nullable=true)
     */
    private $Etudiant;

    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\Session", cascade={"persist"})
     */
    private $Session;

    /**
     * @var string
     *
     * @ORM\Column(name="type_contrat",type="string", columnDefinition="enum('Apprentissage', 'Professionnalisation')",nullable=true)
     */
    private $typeContrat;


    /**
     * @var string
     *
     * @ORM\Column(name="document", type="string", length=255,nullable=true)
     */
    private $document;






    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set dateDepot
     *
     * @param \DateTime $dateDepot
     * @return Offre
     */
    public function setDateDepot($dateDepot)
    {
        $this->dateDepot = $dateDepot;

        return $this;
    }

    /**
     * Get dateDepot
     *
     * @return \DateTime 
     */
    public function getDateDepot()
    {
        return $this->dateDepot;
    }

    /**
     * Set etatOffre
     *
     * @param string $etatOffre
     * @return Offre
     */
    public function setEtatOffre($etatOffre)
    {
        $this->etatOffre = $etatOffre;

        return $this;
    }

    /**
     * Get etatOffre
     *
     * @return string 
     */
    public function getEtatOffre()
    {
        return $this->etatOffre;
    }

    /**
     * Set licenceConcerne
     *
     * @param string $licenceConcerne
     * @return Offre
     */
    public function setLicenceConcerne($licenceConcerne)
    {
        $this->licenceConcerne = $licenceConcerne;

        return $this;
    }

    /**
     * Get licenceConcerne
     *
     * @return string 
     */
    public function getLicenceConcerne()
    {
        return $this->licenceConcerne;
    }

    /**
     * Set sujet
     *
     * @param string $sujet
     * @return Offre
     */
    public function setSujet($sujet)
    {
        $this->sujet = $sujet;

        return $this;
    }

    /**
     * Get sujet
     *
     * @return string 
     */
    public function getSujet()
    {
        return $this->sujet;
    }

    /**
     * Get titre
     *
     * @return string
     */
    public function getTitre()
    {
        return $this->titre;
    }

    /**
     * Set titre
     *
     * @param string $titre
     * @return Offre
     */
    public function setTitre($titre)
    {
        $this->titre = $titre;
    }

    /**
     * Get Entreprise
     *
     * @return Entreprise
     */
    public function getEntreprise()
    {
        return $this->Entreprise;
    }

    /**
     * Set Entreprise
     *
     * @param Entreprise $Entreprise
     * @return Offre
     */
    public function setEntreprise ($Entreprise)
    {
        $this->Entreprise = $Entreprise;
    }

    /**
     * Get MAP
     *
     * @return MAP
     */
    public function getMAP()
    {
        return $this->MAP;
    }

    /**
     * Set MAP
     *
     * @param MAP $MAP
     * @return Offre
     */
    public function setMAP($MAP)
    {
        $this->MAP = $MAP;
    }

    /**
     * Get Etudiant
     *
     * @return Etudiant
     */
    public function getEtudiant()
    {
        return $this->Etudiant;
    }

    /**
     * Set Etudiant
     *
     * @param Etudiant $Etudiant
     * @return Offre
     */
    public function setEtudiant($Etudiant)
    {
        $this->Etudiant = $Etudiant;
    }





    /**
     * Set session
     *
     * @param \SiteBundle\Entity\Session $session
     *
     * @return Offre
     */
    public function setSession(\SiteBundle\Entity\Session $session = null)
    {
        $this->Session = $session;

        return $this;
    }

    /**
     * Get session
     *
     * @return \SiteBundle\Entity\Session
     */
    public function getSession()
    {
        return $this->Session;
    }

    /**
     * Set typeContrat
     *
     * @param string $typeContrat
     *
     * @return Offre
     */
    public function setTypeContrat($typeContrat)
    {
        $this->typeContrat = $typeContrat;

        return $this;
    }

    /**
     * Get typeContrat
     *
     * @return string
     */
    public function getTypeContrat()
    {
        return $this->typeContrat;
    }

    /**
     * Set document
     *
     * @param string $document
     *
     * @return Offre
     */
    public function setDocument($document)
    {
        $this->document = $document;

        return $this;
    }

    /**
     * Get document
     *
     * @return string
     */
    public function getDocument()
    {
        return $this->document;
    }
}

src/SiteBundle/Entity/Personne.php
<?php

namespace SiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Personne
 *
 * @ORM\Table(name="personne")
 * @ORM\Entity(repositoryClass="SiteBundle\Repository\PersonneRepository")
 */
class Personne
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="Nom", type="string", length=50)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="Prenom", type="string", length=50)
     */
    private $prenom;

    /**
     * @var string
     *
     * @ORM\Column(name="Telephone", type="string", length=20, nullable=true)
     */
    private $telephone;

    /**
     * @var string
     *
     * @ORM\Column(type="string", columnDefinition="enum('M', 'F')",nullable=true)
     */
    private $sexe;

    /**
     * @var string
     *
     * @ORM\Column(name="Mail", type="string", length=50)
     */
    private $mail;



    /**
     * @ORM\OneToOne(targetEntity="SiteBundle\Entity\Adresse", cascade={"persist"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $Adresse;

    /**
     * @var bool
     *
     * @ORM\Column(name="isTuteur", type="boolean", )
     */
    private $isTuteur = false;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Personne
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     * @return Personne
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string 
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Set telephone
     *
     * @param string $telephone
     * @return Personne
     */
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * Get telephone
     *
     * @return string 
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * Set sexe
     *
     * @param string $sexe
     * @return Personne
     */
    public function setSexe($sexe)
    {
        $this->sexe = $sexe;

        return $this;
    }

    /**
     * Get sexe
     *
     * @return string 
     */
    public function getSexe()
    {
        return $this->sexe;
    }

    /**
     * Set mail
     *
     * @param string $mail
     * @return Personne
     */
    public function setMail($mail)
    {
        $this->mail = $mail;

        return $this;
    }

    /**
     * Get mail
     *
     * @return string 
     */
    public function getMail()
    {
        return $this->mail;
    }


    /**
     * Get Adresse
     *
     * @return Adresse
     */
    public function getAdresse()
    {
        return $this->Adresse;
    }

    /**
     * Set Adresse
     *
     * @param Adresse $Adresse
     * @return Personne
     */
    public function setAdresse($Adresse)
    {
        $this->Adresse = $Adresse;
    }

    /**
     * Set isTuteur
     *
     * @param boolean $isTuteur
     * @return Personne
     */
    public function setisTuteur($isTuteur)
    {
        $this->isTuteur = $isTuteur;

        return $this;
    }

    /**
     * Get isTuteur
     *
     * @return boolean
     */
    public function getisTuteur()
    {
        return $this->isTuteur;
    }
}

src/SiteBundle/Controller/DefaultController.php
<?php

namespace SiteBundle\Controller;

use SiteBundle\Entity\EtudiantOffre;
use SiteBundle\Forms\Types\PostulerAnnonce;
use SiteBundle\Forms\Types\RechercheOffresType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpFoundation\Response;

class DefaultController extends Controller
{
    public function indexAction()
    {
        return $this->render('SiteBundle:Default:index.html.twig');
    }

    public function testAction()
    {
        return $this->render('SiteBundle:Default:test.html.twig');
    }

    public function detailAnnonceAction(Request $request)
    {
        $annonceId = $request->get('annonceId');
        $repository = $this
            ->getDoctrine()
            ->getManager()
            ->getRepository('SiteBundle:Offre');

        $offre = $repository->find($annonceId);
        //si l'annonce n'es pas trouvé
        if (null === $offre) {
            throw new NotFoundHttpException("L'annonce n'a pas été trouvée.");
        }

        $form = $this->createForm(PostulerAnnonce::class);
        $error = '';

        if ($request->isMethod('post')) {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $offreEtudiantRepository = $this
                    ->getDoctrine()
                    ->getManager()
                    ->getRepository('SiteBundle:EtudiantOffre');
                $error = $offreEtudiantRepository->enregistrerOffre(
                    $this->getUser()->getIdEtudiant()
                    , $form->getData()
                    , $offre);
                $this->addFlash('info', "Votre candidature a bien été pris en compte.");
            }
        }

        return $this->render(
            'SiteBundle:Default:detailsAnnonce.html.twig'
            , ['offre' => $offre, 'annonceId' => $annonceId
                , 'form' => $form->createView()
                , 'errorEtudiant' => $error]
        );
    }

    public function listeOffresAction(Request $request)
    {
        $form = $this->createForm(RechercheOffresType::class);
        $offres = array();
        if ($request->isMethod('post')) {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $data = $form->getData();
                $repository = $this
                    ->getDoctrine()
                    ->getManager()
                    ->getRepository('SiteBundle:Offre');
                $offres = $repository->findOffresByData($data);
            }
        } else {
            $repository = $this
                ->getDoctrine()
                ->getManager()
                ->getRepository('SiteBundle:Offre');
            $offres = $repository->findBy(array('etatOffre' => 'En ligne'));
        }

        return $this->render('SiteBundle:Default:liste_offres.html.twig'
            , ['form' => $form->createView()
                , 'offres' => $offres]);
    }

    public function impressionAnnonceAction(Request $request)
    {
        $annonceId = $request->get('annonceId');
        $repository = $this
            ->getDoctrine()
            ->getManager()
            ->getRepository('SiteBundle:Offre');

        $offre = $repository->find($annonceId);
        //si l'annonce n'es pas trouvé
        if (null === $offre) {
            throw new NotFoundHttpException("L'annonce n'a pas été trouvée.");
        }


        $html = $this->renderView('SiteBundle:Default:impressionAnnonce.html.twig'
            , ['offre' => $offre, 'annonceId' => $annonceId]
        );

        return new Response(
            $this->get('knp_snappy.pdf')->getOutputFromHtml($html),
            200,
            array(
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'attachment; filename="Annonce.pdf"'
            )
        );
    }
}

src/SiteBundle/Resources/views/Default/ajoutAnnonce.html.twig
{% extends '::base.html.twig' %}
{% form_theme form 'bootstrap_3_layout.html.twig' %}


{% block body %}

    <h1>Ajouter une annonce</h1>

    {{ form_start(form) }}
    <label for="map">Maitre apprentissage</label>
    <select name="map">
        {% for map in maps %}
            <option value="{{ map.id }}">{{ map.laPersone.nom }} {{ map.laPersone.prenom }}</option>
        {% endfor %}
    </select>

    <a data-toggle="modal" data-target="#creerMap">
        Créer un Maitre d'apprentissage
    </a>

    {{ form_end(form) }}

    <!-- Modal -->

    <div id="creerMap" class="modal fade" role="dialog">

        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">

                    <button type="button" class="close" data-dismiss="modal">&times;</button>

                    <h4 class="modal-title text-center">Créez un Maitre d'apprentissage</h4>

                </div>
                <div class="modal-body">
                    {{ form(form2) }}
                </div>
            </div>

        </div>
    </div>


    {% block javascripts %}
        <script type="text/javascript">
            {% if bool %}
            jQuery(document).ready(function ($) {

                $('#creerMap').modal('show');

            });
            {% endif %}
        </script>
    {% endblock %}

{% endblock %}

src/SiteBundle/Resources/views/Default/detailsAnnonce.html.twig
{% extends '::base.html.twig' %}
{% form_theme form 'bootstrap_3_layout.html.twig' %}
{% block title %}
    Détails de l'offre {{ offre.titre }}
{% endblock %}


{% block body %}
    <h1 class="text-center margB20">{{ offre.titre }} </h1>

    <div class="row">
        <div id="description" class="col-sm-6 container">
            <h3>Description de l'entreprise</h3>
            <p>{{ offre.entreprise.description }}</p>
            <h3>Description de l'offre</h3>
            <p>{{ offre.sujet }} {% if  offre.document is not empty and offre.document is not null  %} <a target="_blank" href="{{ asset(offre.document) }}">Consulter le sujet de l'offre <span
                            class="glyphicon glyphicon-eye-open "></span></a> {% endif %}</p>
        </div>
        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Coordonnées</h3>
                </div>
                <div class="panel-body">
                    <address>
                        <strong>{{ offre.entreprise.raisonSocial }}</strong><br>
                        {{ offre.entreprise.adresse.adresse }}<br>
                        {{ offre.entreprise.adresse.commune }}, {{ offre.entreprise.adresse.codePostal }}<br>
                    </address>
                    <p><strong>Contact :</strong></p>
                    <dl class="dl-horizontal">
                        <dt>nom</dt>
                        <dd>{{ offre.entreprise.nom }}</dd>
                        <dt>prenom</dt>
                        <dd>{{ offre.entreprise.prenom }}</dd>
                        <dt>mail</dt>
                        <dd>{{ offre.entreprise.mail }}</dd>
                        <dt>téléphone</dt>
                        <dd>{{ offre.entreprise.telephone }}</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
    {% set route = app.request.attributes.get('_route') %}
    {% if route is sameas("site_detailsAnnonceEtudiant") %}
        <button class="btn btn-lg btn-primary center-block" data-toggle="modal" data-target="#postulerOffre">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            Postuler à cette offre
        </button>
        <a class="btn btn-lg btn-success" href="{{ path('site_impressionAnnonceEtudiant', {'annonceId': offre.id }) }}"
           target="_blank">
            <span class="glyphicon glyphicon-print" aria-hidden="true"></span>
            Imprimer l'offre
        </a>

        <!-- Modal -->
        <div id="postulerOffre" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title text-center">Postuler</h4>
                    </div>
                    <div class="modal-body">
                        <!-- Si l'étudiant ne posssede pas de CV on lui propose d'aller sur l'accuueil etudiant et de l'importer -->
                        {% if app.user.idEtudiant is null or app.user.idEtudiant.cv is null or app.user.idEtudiant.cv is sameas("") %}
                            <div class="alert alert-danger" role="alert">
                                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                <span class="sr-only">Error:</span>
                                <strong>Vous ne possédé pas de CV,</strong> vous devez en importer ou en créer un pour
                                pouvoir
                                postuler à cette offre.
                                <p><a class="alert-link" href="{{ path('site_accueilEtudiant') }}">Cliquez ici pour
                                        pouvoir importer
                                        votre CV.</a></p>
                            </div>
                            <button type="button" class="btn btn-default center-block" data-dismiss="modal">Fermer
                            </button>
                        {% else %}
                            <h5><strong>Nom :</strong> {{ app.user.idEtudiant.laPersone.nom }}</h5>
                            <h5><strong>Prenom :</strong> {{ app.user.idEtudiant.laPersone.prenom }}</h5>
                            <h5><strong>CV :</strong> <a href="{{ asset(app.user.idEtudiant.cv) }}" target="_blank">Voir
                                    mon CV</a></h5>
                            {{ form(form) }}
                            {% if errorEtudiant is not sameas('') %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                                aria-hidden="true">&times;</span></button>
                                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                    <span class="sr-only">Error:</span>
                                    <strong>Une erreur s'est produite : </strong> {{ errorEtudiant }}
                                </div>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>
    {% elseif route is sameas("site_detailsAnnonceResponsable") %}

        <a class="btn btn-success" href="{{ path('validation_Annonce', {'offreId': offre.id }) }}">
            Valider
        </a>
        <button class="btn btn-warning" data-toggle="modal" data-target="#modifOffre" id="bouttonmodif">
            Demande de modification
        </button>

        <button class="btn btn-danger" data-toggle="modal" data-target="#refuserOffre">
            Refuser
        </button>

        <a class="btn btn_primary" href="{{ path('acceuil_responsable') }}">
            Retour
        </a>


        <!-- Modal -->
        <div id="modifOffre" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title text-center">Demande de modification</h4>
                    </div>
                    <div class="modal-body">

                        {{ form_start(form_modif, {'attr': {'id':'formModifier'}}) }}
                        {{ form_widget(form_modif) }}
                        {{ form_end(form_modif) }}
                    </div>
                </div>

            </div>
        </div>

        <div id="refuserOffre" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title text-center">Refuser cette offre d'aternance</h4>
                    </div>
                    <div class="modal-body">
                        {{ form_start(form_refus) }}
                        {{ form_widget(form_refus) }}
                        {{ form_end(form_refus) }}

                    </div>
                </div>

            </div>
        </div>

    {% endif %}
{% endblock %}

{% block javascripts %}
    {% set route = app.request.attributes.get('_route') %}

    <script type="text/javascript">
        $(function(){
            {% set route = app.request.attributes.get('_route') %}
            {% if route is sameas("site_detailsAnnonceEtudiant") %}
                {% if errorEtudiant is not sameas('') %}
                $('#postulerOffre').modal('show');
                {% endif %}
            {% elseif route is sameas("site_detailsAnnonceResponsable") %}
                {%if bool2 %}
                $(function(){
                    $('#refuserOffre').modal('show');
                });
                    {% endif %}
                {% if bool1 %}
                $('#modifOffre').modal('show');
                             {% endif %}
            {% endif %}

        });

    </script>
{% endblock %}

src/SiteBundle/Resources/views/Default/edditAnnonce.html.twig
{% extends '::base.html.twig' %}
{% form_theme form 'bootstrap_3_layout.html.twig' %}


{% block body %}

    <h1>Modification de l'annonce</h1>

    {{ form_start(form) }}
    <label for="map">Maitre apprentissage</label>
    <select name="map">
        {% for map in maps %}
            <option value="{{ map.id}}" {% if annonce.mAP.id is sameas(map.id)%} selected {% endif %}" >{{ map.laPersone.nom}} {{ map.laPersone.prenom }}</option>
        {% endfor %}
    </select>

    <a data-toggle="modal" data-target="#creerMap">
        Créer un Maitre d'apprentissage
    </a>

    {{ form_end(form) }}

    <!-- Modal -->

    <div id="creerMap" class="modal fade" role="dialog">

        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">

                    <button type="button" class="close" data-dismiss="modal">&times;</button>

                    <h4 class="modal-title text-center">Créez un Maitre d'apprentissage</h4>

                </div>
                <div class="modal-body">
                    {{ form(form2) }}
                </div>
            </div>

        </div>
    </div>


    {% block javascripts %}
        <script type="text/javascript">
            {% if bool %}
            jQuery(document).ready(function ($) {

                $('#creerMap').modal('show');

            });
            {% endif %}
        </script>
    {% endblock %}

{% endblock %}

src/SiteBundle/Resources/views/Default/impressionAnnonce.html.twig
{% extends '::baseImpression.html.twig' %}

{% block body %}
    <h1 class="text-center margB20">Details de l'annonce n° {{ offre.id }} </h1>

    <div class="row">
        <div class="col-sm-1"></div>
        <div id="description" class="col-sm-10">
            <h3>Titre : {{ offre.titre }}</h3>

            <h3>Description de l'offre</h3>
            <p>{{ offre.sujet }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Coordonnées de l'entreprise </h3>
                </div>
                <div class="panel-body">
                    <address>
                        <strong>{{ offre.entreprise.raisonSocial }}</strong><br>
                        {{ offre.entreprise.adresse.adresse }}<br>
                        {{ offre.entreprise.adresse.commune }}, {{ offre.entreprise.adresse.codePostal }}<br>
                    </address>
                    <p><strong>Contact :</strong></p>
                    <dl>
                        <dd>Nom: {{ offre.entreprise.nom }}</dd>
                        <dd>Prenom : {{ offre.entreprise.prenom }}</dd>
                        <dd>Mail : {{ offre.entreprise.mail }}</dd>
                        <dd>Téléphone : {{ offre.entreprise.telephone }}</dd>
                        <dd>Description :{{ offre.entreprise.description }}</dd>

                    </dl>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/SiteBundle/Resources/views/Default/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="margTop50">

        <div class="col-sm-5 block-bleu">
            <h1>Je suis Étudiant/Alternant</h1>
            <p>
                Pour pouvoir vous connecter à cet espace, vous devez vous connecter à l'aide d'un identifiant et mot de passe reçu sur votre adresse mail.
                Adresse mail que vous avez renseigné sur CIEL2 ou directement au responsable de la licence.
                Si vous n'avez toujours pas reçu ce mail, vous ne pourrez pas aller plus loin.
            </p>
        </div>
        <div class="col-sm-2">
        </div>
        <div class="col-sm-5 block-bleu">
            <h1>Je souhaite recruter un alternant</h1>
            <p>
                Pouvoir ce connecter à cet espace, vous devez vous connecter à l'aide d'un identifiant et mot de passe reçu sur votre adresse mail.
                Adresse mail que vous avez renseigné en vous inscrivant.
                Si vous n'avez toujours pas reçu ce mail, vous ne pourrez pas aller plus loin.
            </p>
            <a href="{{ path('inscriptionEntreprise') }}" type="button" class="btn btn-primary btn-lg center-block">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> S'inscrire
            </a>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/style/index.css') }}" type="text/css"/>
{% endblock %}

{% block title %}Page d'accueil{% endblock %}

src/SiteBundle/Resources/views/Default/liste_offres.html.twig
{% form_theme form 'bootstrap_3_horizontal_layout.html.twig' %}
{% extends 'base.html.twig' %}
{% block title %}
    Liste des offres
{% endblock %}
{% block body %}
    <h1 class="text-center">Offres d'alternance des entreprises</h1>
    {{ form(form) }}

    <h2>Liste des offres</h2>
    <div class="list-group">
        {% if 'site_listeOffreEntreprise' == app.request.attributes.get('_route') %}
            {% for offre in offres %}

                <a class="list-group-item" href="{{ path('site_detailsAnnonceEntreprise', {'annonceId': offre.id }) }}">

                    <h3>{{ offre.entreprise.raisonSocial }} : {{ offre.titre }}
                        <small>{{ offre.entreprise.adresse.commune }} - {{ offre.entreprise.adresse.adresse }}</small>
                    </h3>
                    <p>{{ offre.sujet }}</p>
                </a>

            {% endfor %}
        {% else %}
            {% for offre in offres %}

                <a class="list-group-item" href="{{ path('site_detailsAnnonceEtudiant', {'annonceId': offre.id }) }}">

                    <h3>{{ offre.entreprise.raisonSocial }} : {{ offre.titre }}
                        <small>{{ offre.entreprise.adresse.commune }} - {{ offre.entreprise.adresse.adresse }}</small>
                    </h3>
                    <p>{{ offre.sujet }}</p>
                </a>

            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

src/SiteBundle/Resources/views/Default/test.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Bienvenue</h1>
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/style/index.css') }}" type="text/css"/>
{% endblock %}

{% block title %}Page d'accueil{% endblock %}