src/SiteBundle/Entity/Adresse.php
<?php

namespace SiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Intl\Intl;

/**
 * Adresse
 *
 * @ORM\Table(name="adresse")
 * @ORM\Entity(repositoryClass="SiteBundle\Repository\AdresseRepository")
 */
class Adresse
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="Adresse", type="string", length=255)
     */
    private $adresse;

    /**
     * @var string
     *
     * @ORM\Column(name="CodePostal", type="string", length=6)
     */
    private $codePostal;

    /**
     * @var string
     *
     * @ORM\Column(name="Commune", type="string", length=50)
     */
    private $commune;

    /**
     * @var string
     *
     * @ORM\Column(name="Pays", type="string", length=50)
     */
    private $pays;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set adresse
     *
     * @param string $adresse
     * @return Adresse
     */
    public function setAdresse($adresse)
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * Get adresse
     *
     * @return string 
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * Set codePostal
     *
     * @param string $codePostal
     * @return Adresse
     */
    public function setCodePostal($codePostal)
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    /**
     * Get codePostal
     *
     * @return string 
     */
    public function getCodePostal()
    {
        return $this->codePostal;
    }

    /**
     * Set commune
     *
     * @param string $commune
     * @return Adresse
     */
    public function setCommune($commune)
    {
        $this->commune = $commune;

        return $this;
    }

    /**
     * Get commune
     *
     * @return string 
     */
    public function getCommune()
    {
        return $this->commune;
    }

    /**
     * Set pays
     *
     * @param string $pays
     * @return Adresse
     */
    public function setPays($pays)
    {
        $this->pays = $pays;

        return $this;
    }

    /**
     * Get pays
     *
     * @return string 
     */
    public function getPays()
    {
        return $this->pays;
    }


    public function getNomPays()
    {
        return Intl::getRegionBundle()->getCountryName($this->getPays());
    }
}

src/SiteBundle/Entity/Etudiant.php
<?php

namespace SiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Etudiant
 *
 * @ORM\Table(name="etudiant")
 * @ORM\Entity(repositoryClass="SiteBundle\Repository\EtudiantRepository")
 */
class Etudiant
{


    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\Session", cascade={"persist"})
     */
    private $Session;

    /**
     * @ORM\OneToOne(targetEntity="SiteBundle\Entity\DossierInscription", cascade={"persist"})
     */
    private $DossierInscription;
    /**
     * @ORM\OneToOne(targetEntity="SiteBundle\Entity\Personne", cascade={"persist"})
     */
    private $laPersone;
    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\Personne", cascade={"persist"})
     */
    private $leTuteur;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=true)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="DateNaissance", type="date", nullable=true)
     */
    private $dateNaissance;

    /**
     * @var string
     *
     * @ORM\Column(name="CV", type="string", length=255, nullable=true)
     */
    private $cV;

    /**
     * @var string
     *
     * @ORM\Column(type="string", columnDefinition="enum('METINET', 'IEM')",nullable=true)
     */
    private $typeLicence;
    /**
     * @var string
     *
     * @ORM\Column(name="VilleNaissance", type="string", length=255, nullable=true)
     */
    private $villeNaissance;
    /**
     * @var string
     *
     * @ORM\Column(name="Nationalite", type="string", length=255, nullable=true)
     */
    private $nationalite;
    /**
     * @var string
     *
     * @ORM\Column(name="NumeroDossierCandidature", type="string", length=255, nullable=true)
     */
    private $numeroDossierCandidature;

    /**
     * @ORM\OneToOne(targetEntity="SiteBundle\Entity\DossierAdmission", cascade={"persist"})
     */
    private $dossierAdmission;

    /**
     * @var bool
     *
     * @ORM\Column(name="statut", type="boolean", nullable=true)
     */
    private $statut;

    /**
     * @var boolean $isAdmissible
     *
     * @ORM\Column(name="isAdmissible", type="boolean")
     */
    private $isAdmissible = false;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set dateNaissance
     *
     * @param \DateTime $dateNaissance
     * @return Etudiant
     */
    public function setDateNaissance($dateNaissance)
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    /**
     * Get dateNaissance
     *
     * @return \DateTime
     */
    public function getDateNaissance()
    {
        return $this->dateNaissance;
    }

    /**
     * Set cV
     *
     * @param string $cV
     * @return Etudiant
     */
    public function setCV($cV)
    {
        $this->cV = $cV;

        return $this;
    }

    /**
     * Get cV
     *
     * @return string
     */
    public function getCV()
    {
        return $this->cV;
    }

    /**
     * Set typeLicence
     *
     * @param string $typeLicence
     * @return Etudiant
     */
    public function setTypeLicence($typeLicence)
    {
        $this->typeLicence = $typeLicence;

        return $this;
    }

    /**
     * Get typeLicence
     *
     * @return string
     */
    public function getTypeLicence()
    {
        return $this->typeLicence;
    }

    /**
     * Set villeNaissance
     *
     * @param string $villeNaissance
     * @return Etudiant
     */
    public function setVilleNaissance($villeNaissance)
    {
        $this->villeNaissance = $villeNaissance;

        return $this;
    }


    /**
     * Get villeNaissance
     *
     * @return string
     */
    public function getVilleNaissance()
    {
        return $this->villeNaissance;
    }

    /**
     * Set nationalite
     *
     * @param string $nationalite
     * @return Etudiant
     */
    public function setNationalite($nationalite)
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * Get nationalite
     *
     * @return string
     */
    public function getNationalite()
    {
        return $this->nationalite;
    }

    /**
     * Set numeroDossierCandidature
     *
     * @param string $numeroDossierCandidature
     * @return Etudiant
     */
    public function setNumeroDossierCandidature($numeroDossierCandidature)
    {
        $this->numeroDossierCandidature = $numeroDossierCandidature;

        return $this;
    }

    /**
     * Get numeroDossierCandidature
     *
     * @return string
     */
    public function getNumeroDossierCandidature()
    {
        return $this->numeroDossierCandidature;
    }

    /**
     * Set statut
     *
     * @param boolean $statut
     * @return Etudiant
     */
    public function setStatut($statut)
    {
        $this->statut = $statut;

        return $this;
    }

    /**
     * Get statut
     *
     * @return boolean
     */
    public function getStatut()
    {
        return $this->statut;
    }

    /**
     * Get laPersone
     *
     * @return Personne
     */
    public function getLaPersone()
    {
        return $this->laPersone;
    }

    /**
     * Set laPersone
     *
     * @param Personne $laPersone
     * @return Etudiant
     */
    public function setLaPersone(Personne $laPersone)
    {
        $this->laPersone = $laPersone;
    }

    /**
     * Get DossierInscription
     *
     * @return DossierInscription
     */
    public function getInscription()
    {
        return $this->DossierInscription;
    }

    /**
     * Set DossierInscription
     *
     * @param DossierInscription $DossierInscription
     * @return Etudiant
     */
    public function setInscription($DossierInscription)
    {
        $this->DossierInscription = $DossierInscription;
    }

    public function getAge()
    {
        $dateInterval = $this->dateNaissance->diff(new \DateTime());

        return $dateInterval->y;
    }

    /**
     * Get leTuteur
     *
     * @return Personne
     */
    public function getleTuteur()
    {
        return $this->leTuteur;
    }

    /**
     * Set leTuteur
     *
     * @param Personne $leTuteur
     * @return Personne
     */
    public function setleTuteur(Personne $leTuteur)
    {
        $this->leTuteur = $leTuteur;
    }

    /**
     * Set dossierInscription
     *
     * @param \SiteBundle\Entity\DossierInscription $dossierInscription
     *
     * @return Etudiant
     */
    public function setDossierInscription(\SiteBundle\Entity\DossierInscription $dossierInscription = null)
    {
        $this->DossierInscription = $dossierInscription;

        return $this;
    }

    /**
     * Get dossierInscription
     *
     * @return \SiteBundle\Entity\DossierInscription
     */
    public function getDossierInscription()
    {
        return $this->DossierInscription;
    }

    /**
     * Set session
     *
     * @param \SiteBundle\Entity\Session $session
     *
     * @return Etudiant
     */
    public function setSession(\SiteBundle\Entity\Session $session = null)
    {
        $this->Session = $session;

        return $this;
    }

    /**
     * Get session
     *
     * @return \SiteBundle\Entity\Session
     */
    public function getSession()
    {
        return $this->Session;
    }

    /**
     * Set isAdmissible
     *
     * @param boolean $isAdmissible
     *
     * @return Etudiant
     */
    public function setIsAdmissible($isAdmissible)
    {
        $this->isAdmissible = $isAdmissible;

        return $this;
    }

    /**
     * Get isAdmissible
     *
     * @return boolean
     */
    public function getIsAdmissible()
    {
        return $this->isAdmissible;
    }

    /**
     * Set dossierAdmission
     *
     * @param \SiteBundle\Entity\DossierAdmission $dossierAdmission
     *
     * @return Etudiant
     */
    public function setDossierAdmission(\SiteBundle\Entity\DossierAdmission $dossierAdmission = null)
    {
        $this->dossierAdmission = $dossierAdmission;

        return $this;
    }

    /**
     * Get dossierAdmission
     *
     * @return \SiteBundle\Entity\DossierAdmission
     */
    public function getDossierAdmission()
    {
        return $this->dossierAdmission;
    }
}

src/SiteBundle/Entity/Offre.php
<?php

namespace SiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use SiteBundle\Entity\Session;

/**
 * Offre
 *
 * @ORM\Table(name="offre")
 * @ORM\Entity(repositoryClass="SiteBundle\Repository\OffreRepository")
 */
class Offre
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="DateDepot", type="date")
     */
    private $dateDepot;


    /**
     * @var string
     *
     * @ORM\Column(name="etat_offre", type="string", columnDefinition="enum('En attente de validation','En ligne','Pourvue','En attente de modification','Refuser')" ,nullable=true , options={"default":"0"})
     */
    private $etatOffre;


    /**
     * @var string
     *
     * @ORM\Column(name="licence_concerne",type="string", columnDefinition="enum('METINET', 'IEM')",nullable=true)
     */
    private $licenceConcerne;

    /**
     * @var string
     *
     * @ORM\Column(name="Sujet", type="text",nullable=true)
     */
    private $sujet;

    /**
     * @var string
     *
     * @ORM\Column(name="Titre", type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\Entreprise")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Entreprise;

    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\MAP")
     * @ORM\JoinColumn(nullable=false)
     */
    private $MAP;

    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\Etudiant")
     * @ORM\JoinColumn(nullable=true)
     */
    private $Etudiant;

    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\Session", cascade={"persist"})
     */
    private $Session;

    /**
     * @var string
     *
     * @ORM\Column(name="type_contrat",type="string", columnDefinition="enum('Apprentissage', 'Professionnalisation')",nullable=true)
     */
    private $typeContrat;


    /**
     * @var string
     *
     * @ORM\Column(name="document", type="string", length=255,nullable=true)
     */
    private $document;






    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set dateDepot
     *
     * @param \DateTime $dateDepot
     * @return Offre
     */
    public function setDateDepot($dateDepot)
    {
        $this->dateDepot = $dateDepot;

        return $this;
    }

    /**
     * Get dateDepot
     *
     * @return \DateTime 
     */
    public function getDateDepot()
    {
        return $this->dateDepot;
    }

    /**
     * Set etatOffre
     *
     * @param string $etatOffre
     * @return Offre
     */
    public function setEtatOffre($etatOffre)
    {
        $this->etatOffre = $etatOffre;

        return $this;
    }

    /**
     * Get etatOffre
     *
     * @return string 
     */
    public function getEtatOffre()
    {
        return $this->etatOffre;
    }

    /**
     * Set licenceConcerne
     *
     * @param string $licenceConcerne
     * @return Offre
     */
    public function setLicenceConcerne($licenceConcerne)
    {
        $this->licenceConcerne = $licenceConcerne;

        return $this;
    }

    /**
     * Get licenceConcerne
     *
     * @return string 
     */
    public function getLicenceConcerne()
    {
        return $this->licenceConcerne;
    }

    /**
     * Set sujet
     *
     * @param string $sujet
     * @return Offre
     */
    public function setSujet($sujet)
    {
        $this->sujet = $sujet;

        return $this;
    }

    /**
     * Get sujet
     *
     * @return string 
     */
    public function getSujet()
    {
        return $this->sujet;
    }

    /**
     * Get titre
     *
     * @return string
     */
    public function getTitre()
    {
        return $this->titre;
    }

    /**
     * Set titre
     *
     * @param string $titre
     * @return Offre
     */
    public function setTitre($titre)
    {
        $this->titre = $titre;
    }

    /**
     * Get Entreprise
     *
     * @return Entreprise
     */
    public function getEntreprise()
    {
        return $this->Entreprise;
    }

    /**
     * Set Entreprise
     *
     * @param Entreprise $Entreprise
     * @return Offre
     */
    public function setEntreprise ($Entreprise)
    {
        $this->Entreprise = $Entreprise;
    }

    /**
     * Get MAP
     *
     * @return MAP
     */
    public function getMAP()
    {
        return $this->MAP;
    }

    /**
     * Set MAP
     *
     * @param MAP $MAP
     * @return Offre
     */
    public function setMAP($MAP)
    {
        $this->MAP = $MAP;
    }

    /**
     * Get Etudiant
     *
     * @return Etudiant
     */
    public function getEtudiant()
    {
        return $this->Etudiant;
    }

    /**
     * Set Etudiant
     *
     * @param Etudiant $Etudiant
     * @return Offre
     */
    public function setEtudiant($Etudiant)
    {
        $this->Etudiant = $Etudiant;
    }





    /**
     * Set session
     *
     * @param \SiteBundle\Entity\Session $session
     *
     * @return Offre
     */
    public function setSession(\SiteBundle\Entity\Session $session = null)
    {
        $this->Session = $session;

        return $this;
    }

    /**
     * Get session
     *
     * @return \SiteBundle\Entity\Session
     */
    public function getSession()
    {
        return $this->Session;
    }

    /**
     * Set typeContrat
     *
     * @param string $typeContrat
     *
     * @return Offre
     */
    public function setTypeContrat($typeContrat)
    {
        $this->typeContrat = $typeContrat;

        return $this;
    }

    /**
     * Get typeContrat
     *
     * @return string
     */
    public function getTypeContrat()
    {
        return $this->typeContrat;
    }

    /**
     * Set document
     *
     * @param string $document
     *
     * @return Offre
     */
    public function setDocument($document)
    {
        $this->document = $document;

        return $this;
    }

    /**
     * Get document
     *
     * @return string
     */
    public function getDocument()
    {
        return $this->document;
    }
}

src/SiteBundle/Resources/views/Etudiant/ImpressionDossierInscriptionPage4.html.twig
{% extends '::ImpressionDossierInscription.html.twig' %}
{% block page4 %}

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-info">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <img class="img-Impression pull-right" src="{{ absolute_url(asset('image/logo-lyon1.png')) }}" alt="Université Claude Bernard Lyon 1" />
                        </div>
                    </div>
                    <br><br>
                    <div class="row">
                        <div class="col-sm-12">
                            <p>La loi n°78-17 du 6 janvier 1978 relative à l'informatique, aux fichiers et aux libertés,
                                vous donne un droit d'accès et rectification aux données vous concernant.
                                Vous pourrez exercer ce droit en adressant un courrier à :
                            </p>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            <p> Directeur Général des Services de l'Université Lyon1 </p>
                            <p> Maison de l'Université </p>
                            <p> 43 bd du 11 novembre 1918 </p>
                            <p> 69622 VILLEURBANNE Cedex </p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-6">
                            <p> Je Soussigné(e) </p>
                        </div>
                        <div class="col-sm-6">
                            <p> déclare :  </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <ul>
                                <li>adhérer à la charte informatique de l'Université Lyon1</li>
                                <li>pour les étudiants de première année commune aux études de Santé, adhérer à : UFR de Médeceine Charte de l'étudiant</li>
                                <li>être informé(e) du fait que le non respect de la législation ainsi que des règles fixées par la charte de l'Université peut impliquer,
                                    sans préjuger d'éventuelles poursuites pénales, la comparution devant la section disciplinaire de l'Université.</li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            <p> Signature précédée de la mention manuscrite "lu et approuvé" : </p>
                        </div>
                    </div>
                    <br><br><br><br><br><br><br><br><br>
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            <p> Je certifie sincères et veritables les renseignements fournis et je déclare avoir pris connaissance des instructions jointes au dossier. </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <p> À </p>
                        </div>
                        <div class="col-sm-6">
                            <p> le {{ "now"|date("m/d/Y") }}  </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            <p> Signature : </p>
                        </div>
                    </div>
                    <br><br><br>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

src/SiteBundle/Resources/views/Etudiant/detailsEntreprise.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    Detail entreprise {{ entreprise.raisonSocial }}
{% endblock %}
{% block body %}
    <h1>{{ entreprise.raisonSocial }}</h1>
    <div class="row">
        <div class="col-md-3"><strong>Raison sociale :</strong></div>
        <div class="col-md-9">{{ entreprise.raisonSocial }}</div>
        <div class="col-md-3"><strong>Description :</strong></div>
        <div class="col-md-9">{{ entreprise.description }}</div>
        <div class="col-md-3"><strong>Adresse :</strong></div>
        <div class="col-md-9">{{ entreprise.adresse.adresse }}</div>
        <div class="col-md-3"><strong>Code postal :</strong></div>
        <div class="col-md-9">{{ entreprise.adresse.codePostal }}</div>
        <div class="col-md-3"><strong>Ville :</strong></div>
        <div class="col-md-9">{{ entreprise.adresse.commune }}</div>
        <div class="col-md-3"><strong>Pays :</strong></div>
        <div class="col-md-9">{{ entreprise.adresse.nomPays }}</div>
        <div class="col-md-12"><h3>Contact</h3></div>
        <div class="col-md-3"><strong>Nom :</strong></div>
        <div class="col-md-9">{{ entreprise.nom }}</div>
        <div class="col-md-3"><strong>Prenom :</strong></div>
        <div class="col-md-9">{{ entreprise.prenom }}</div>
        <div class="col-md-3"><strong>E-mail :</strong></div>
        <div class="col-md-9">{{ entreprise.mail }}</div>
        <div class="col-md-3"><strong>Téléphone :</strong></div>
        <div class="col-md-9">{{ entreprise.telephone }}</div>
        {% if entreprise.siteWeb is not null %}
            <div class="col-md-3"><strong>Site web :</strong></div>
            <div class="col-md-9"><a href="{{ entreprise.siteWeb }}" target="_blank">{{ entreprise.siteWeb }}</a></div>
        {% endif %}

    </div>
    <div class="text-center">
        <a class="btn btn-default" href="{{ path('site_accueilEtudiant') }}">Retour</a>
    </div>
{% endblock %}

src/SiteBundle/Resources/views/Etudiant/liste_offre_postuler_Etudiant.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">Annonces où vous avez été retenu</a></li>
        <li><a data-toggle="tab" href="#menu1">Annonces où vous avez postulé</a></li>
        <li><a data-toggle="tab" href="#menu2">Annonces où vous avez été refusé</a></li>
    </ul>

    <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3>Annonces où vous avez été retenu</h3>
            </div>
            <div class="panel-body">
                <p> Parmis ces offres où vous avez été retenu , vous devez en validez qu'une seule qui sera definitive. Si vous n'avez pas d'offre dans section continuez a <a href="{{ path('site_listeOffreEtudiant') }}">postulez à des offres.</a> </p>

                <table class="table table-bordered">
                    <tr>
                        <th class="col-md-2 text-center">Date</th>
                        <th class="col-md-2 text-center">Intitulé de l'annonce</th>
                        <th class="col-md-2 text-center">Entreprise</th>
                        <th class="col-md-2 text-center">Lp concerné</th>
                        <th class="col-md-2 text-center">Action</th>

                    </tr>
                    {% for offre in offresV %}
                        <tr>
                            <td>{{ offre.date|date("d/m/Y") }}</td>
                            <td><a                       href="{{ path('site_detailsAnnonceEtudiant', {'annonceId': offre.offre.id }) }}">{{ offre.offre.titre }}</a></td>
                            <td> <a                       href="{{ path('detailsEntreprise', {'entrepriseId': offre.offre.entreprise.id }) }}">{{ offre.offre.entreprise.raisonSocial }} </a></td>
                            <td>{{ offre.offre.licenceConcerne }}</td>
                            <td class="text-center"> <div class="btn-group">
                                    <button class="btn">Action</button>
                                    <button class="btn dropdown-toggle" data-toggle="dropdown"> <span class="caret"></span> </button>
                                    <ul class="dropdown-menu">
                                        <li><a href="{{ path('site_accepterOffreEtudiant', {'annonceId': offre.offre.id}) }}">Valider cette offre <span class="glyphicon glyphicon-ok"></span></a></li>
                                        <li><a href="{{ path('site_refuserOffreEtudiant', {'annonceId': offre.id}) }}">Refuser cette offre <span class="glyphicon glyphicon-remove"></span></a></li>

                                    </ul>
                                </div>
                            </td>
                        </tr>

                    {% endfor %}
                </table>
            </div>
        </div>
    </div>



    <div id="menu1" class="tab-pane fade">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3>Annonces où vous avez postulé</h3>
            </div>
            <div class="panel-body">
                <table class="table table-bordered">
                    <tr>
                        <th class="col-md-2 text-center">Date</th>
                        <th class="col-md-2 text-center">Intitulé de l'annonce</th>
                        <th class="col-md-2 text-center">Entreprise</th>
                        <th class="col-md-2 text-center">Lp concerné</th>

                    </tr>
                    {% for offre in offresP %}
                        <td> {{ offre.date|date("d/m/Y") }} </td>
                        <td><a href="{{ path('site_detailsAnnonceEtudiant', {'annonceId': offre.offre.id }) }}">{{ offre.offre.titre }}</a></td>
                        <td> <a href="{{path('detailsEntreprise', {'entrepriseId': offre.offre.entreprise.id }) }}">{{ offre.offre.entreprise.raisonSocial  }}</a>  </td>
                        <td>{{ offre.offre.licenceConcerne }}</td>

                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

    <div id="menu2" class="tab-pane fade">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3>Annonces refusées</h3>
        </div>
        <div class="panel-body">
            <p>Voici les annonces où vous avez postulés et où vous n'avez pas eté retenu ou bien les annonces que vous avez refusées.</p>


            <table class="table table-bordered">
                <tr>
                    <th class="col-md-2 text-center">Date</th>
                    <th class="col-md-2 text-center">Intitulé de l'annonce</th>
                    <th class="col-md-2 text-center">Entreprise</th>
                    <th class="col-md-2 text-center">Lp concerné</th>
                </tr>
                {% for offre in offresR %}
                    <tr>
                        <td>{{ offre.date|date("d/m/Y") }}</td>
                        <td>{{ offre.offre.titre }}</td>
                        <td> <a href="{{ path('detailsEntreprise', {'entrepriseId': offre.offre.entreprise.id })     }}">{{ offre.offre.entreprise.raisonSocial }} </a></td>
                        <td>{{ offre.offre.licenceConcerne }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>


{% endblock %}

src/SiteBundle/Resources/views/Etudiant/modification_mot_de_passe.html.twig
{% extends '::base.html.twig' %}
{% form_theme form 'bootstrap_3_layout.html.twig' %}
{% block body %}
    <h1>Modifier son mot de passe</h1>
    {{ form(form) }}
{% endblock %}

src/SiteBundle/Resources/views/Etudiant/recapOffre.html.twig
{% extends '::base.html.twig' %}

{% block body %}

    <h1>Recapitulatif de votre alternance</h1>

    <label>Licence :</label><p> {{ offre.licenceConcerne }} </p>
    <label>Titre de l'offre</label><p>{{ offre.titre }}</p>
    <label>Sujet</label><p>{{ offre.sujet }} {% if  offre.document is not empty and offre.document is not null  %} <a target="_blank" href="{{ asset(offre.document) }}">Consulter le sujet de l'offre <span
                class="glyphicon glyphicon-eye-open "></span></a> {% endif %} </p>
    <label>Maitre appretissage :</label><p>{{ offre.mAP.laPersone.nom }} {{ offre.mAP.laPersone.prenom }}</p>
    <label>Tuteur Pédagogique :</label>{% if offre.etudiant.leTuteur is not empty %}<p>{{ offre.etudiant.leTuteur.nom }} {{ offre.etudiant.leTuteur.prenom }}</p>{% else %}<p class="text-danger"> Aucun tuteur assigné.</p> {% endif %}
    <label>Type de contrat :</label>{% if offre.typeContrat is not empty %}<p>{{ offre.typeContrat }}</p>{% else %}<p class="text-danger">Aucun type de contrat choisi.</p> {% endif %}

    <label></label><label></label>




{% endblock %}