src/SiteBundle/Entity/Entreprise.php
<?php

namespace SiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Entreprise
 *
 * @ORM\Table(name="entreprise")
 * @ORM\Entity(repositoryClass="SiteBundle\Repository\EntrepriseRepository")
 */
class Entreprise
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="Nom", type="string", length=50)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="Prenom", type="string", length=50)
     */
    private $prenom;

    /**
     * @var string
     *
     * @ORM\Column(name="Mail", type="string", length=50)
     */
    private $mail;

    /**
     * @var string
     *
     * @ORM\Column(name="RaisonSocial", type="string", length=50)
     */
    private $raisonSocial;

    /**
     * @var string
     *
     * @ORM\Column(name="NombrePersonne", type="string", length=50)
     */
    private $nombrePersonne;

    /**
     * @var string
     *
     * @Assert\Regex(
     *     pattern="/[0-9]{14}/",
     *     message="Le numéro siret est invalide. Il doit comporter 14 caractères."
     * )
     *
     * @ORM\Column(name="Siret", type="string", length=50)
     */
    private $siret;

    /**
     * @var string
     *
     * @ORM\Column(name="APE", type="string", length=50)
     */
    private $aPE;

    /**
     * @var string
     *
     * @ORM\Column(name="Description", type="text")
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="SiteWeb", type="string", length=50, nullable=true)
     */
    private $siteWeb;

    /**
     * @var string
     *
     * * @Assert\Regex(
     *     pattern="/[0-9]{10,12}/",
     *     message="Le numéro de téléphone est invalide."
     * )
     *
     * @ORM\Column(name="Telephone", type="string", length=50)
     */
    private $telephone;

    /**
     * @ORM\OneToOne(targetEntity="SiteBundle\Entity\Adresse", cascade={"persist"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $Adresse;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Entreprise
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     * @return Entreprise
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string 
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Set mail
     *
     * @param string $mail
     * @return Entreprise
     */
    public function setMail($mail)
    {
        $this->mail = $mail;

        return $this;
    }

    /**
     * Get mail
     *
     * @return string 
     */
    public function getMail()
    {
        return $this->mail;
    }

    /**
     * Set raisonSocial
     *
     * @param string $raisonSocial
     * @return Entreprise
     */
    public function setRaisonSocial($raisonSocial)
    {
        $this->raisonSocial = $raisonSocial;

        return $this;
    }

    /**
     * Get raisonSocial
     *
     * @return string 
     */
    public function getRaisonSocial()
    {
        return $this->raisonSocial;
    }

    /**
     * Set nombrePersonne
     *
     * @param string $nombrePersonne
     * @return Entreprise
     */
    public function setNombrePersonne($nombrePersonne)
    {
        $this->nombrePersonne = $nombrePersonne;

        return $this;
    }

    /**
     * Get nombrePersonne
     *
     * @return string 
     */
    public function getNombrePersonne()
    {
        return $this->nombrePersonne;
    }

    /**
     * Set siret
     *
     * @param string $siret
     * @return Entreprise
     */
    public function setSiret($siret)
    {
        $this->siret = $siret;

        return $this;
    }

    /**
     * Get siret
     *
     * @return string 
     */
    public function getSiret()
    {
        return $this->siret;
    }

    /**
     * Set aPE
     *
     * @param string $aPE
     * @return Entreprise
     */
    public function setAPE($aPE)
    {
        $this->aPE = $aPE;

        return $this;
    }

    /**
     * Get aPE
     *
     * @return string 
     */
    public function getAPE()
    {
        return $this->aPE;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Entreprise
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set siteWeb
     *
     * @param string $siteWeb
     * @return Entreprise
     */
    public function setSiteWeb($siteWeb)
    {
        $this->siteWeb = $siteWeb;

        return $this;
    }

    /**
     * Get siteWeb
     *
     * @return string 
     */
    public function getSiteWeb()
    {
        return $this->siteWeb;
    }

    /**
     * Set telephone
     *
     * @param string $telephone
     * @return Entreprise
     */
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * Get telephone
     *
     * @return string 
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * Get Adresse
     *
     * @return Adresse
     */
    public function getAdresse()
    {
        return $this->Adresse;
    }

    /**
     * Set Adresse
     *
     * @param Adresse $Adresse
     * @return Entreprise
     */
    public function setAdresse($Adresse)
    {
        $this->Adresse = $Adresse;
    }
}

src/SiteBundle/Entity/Offre.php
<?php

namespace SiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use SiteBundle\Entity\Session;

/**
 * Offre
 *
 * @ORM\Table(name="offre")
 * @ORM\Entity(repositoryClass="SiteBundle\Repository\OffreRepository")
 */
class Offre
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="DateDepot", type="date")
     */
    private $dateDepot;


    /**
     * @var string
     *
     * @ORM\Column(name="etat_offre", type="string", columnDefinition="enum('En attente de validation','En ligne','Pourvue','En attente de modification','Refuser')" ,nullable=true , options={"default":"0"})
     */
    private $etatOffre;


    /**
     * @var string
     *
     * @ORM\Column(name="licence_concerne",type="string", columnDefinition="enum('METINET', 'IEM')",nullable=true)
     */
    private $licenceConcerne;

    /**
     * @var string
     *
     * @ORM\Column(name="Sujet", type="text",nullable=true)
     */
    private $sujet;

    /**
     * @var string
     *
     * @ORM\Column(name="Titre", type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\Entreprise")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Entreprise;

    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\MAP")
     * @ORM\JoinColumn(nullable=false)
     */
    private $MAP;

    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\Etudiant")
     * @ORM\JoinColumn(nullable=true)
     */
    private $Etudiant;

    /**
     * @ORM\ManyToOne(targetEntity="SiteBundle\Entity\Session", cascade={"persist"})
     */
    private $Session;

    /**
     * @var string
     *
     * @ORM\Column(name="type_contrat",type="string", columnDefinition="enum('Apprentissage', 'Professionnalisation')",nullable=true)
     */
    private $typeContrat;


    /**
     * @var string
     *
     * @ORM\Column(name="document", type="string", length=255,nullable=true)
     */
    private $document;






    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set dateDepot
     *
     * @param \DateTime $dateDepot
     * @return Offre
     */
    public function setDateDepot($dateDepot)
    {
        $this->dateDepot = $dateDepot;

        return $this;
    }

    /**
     * Get dateDepot
     *
     * @return \DateTime 
     */
    public function getDateDepot()
    {
        return $this->dateDepot;
    }

    /**
     * Set etatOffre
     *
     * @param string $etatOffre
     * @return Offre
     */
    public function setEtatOffre($etatOffre)
    {
        $this->etatOffre = $etatOffre;

        return $this;
    }

    /**
     * Get etatOffre
     *
     * @return string 
     */
    public function getEtatOffre()
    {
        return $this->etatOffre;
    }

    /**
     * Set licenceConcerne
     *
     * @param string $licenceConcerne
     * @return Offre
     */
    public function setLicenceConcerne($licenceConcerne)
    {
        $this->licenceConcerne = $licenceConcerne;

        return $this;
    }

    /**
     * Get licenceConcerne
     *
     * @return string 
     */
    public function getLicenceConcerne()
    {
        return $this->licenceConcerne;
    }

    /**
     * Set sujet
     *
     * @param string $sujet
     * @return Offre
     */
    public function setSujet($sujet)
    {
        $this->sujet = $sujet;

        return $this;
    }

    /**
     * Get sujet
     *
     * @return string 
     */
    public function getSujet()
    {
        return $this->sujet;
    }

    /**
     * Get titre
     *
     * @return string
     */
    public function getTitre()
    {
        return $this->titre;
    }

    /**
     * Set titre
     *
     * @param string $titre
     * @return Offre
     */
    public function setTitre($titre)
    {
        $this->titre = $titre;
    }

    /**
     * Get Entreprise
     *
     * @return Entreprise
     */
    public function getEntreprise()
    {
        return $this->Entreprise;
    }

    /**
     * Set Entreprise
     *
     * @param Entreprise $Entreprise
     * @return Offre
     */
    public function setEntreprise ($Entreprise)
    {
        $this->Entreprise = $Entreprise;
    }

    /**
     * Get MAP
     *
     * @return MAP
     */
    public function getMAP()
    {
        return $this->MAP;
    }

    /**
     * Set MAP
     *
     * @param MAP $MAP
     * @return Offre
     */
    public function setMAP($MAP)
    {
        $this->MAP = $MAP;
    }

    /**
     * Get Etudiant
     *
     * @return Etudiant
     */
    public function getEtudiant()
    {
        return $this->Etudiant;
    }

    /**
     * Set Etudiant
     *
     * @param Etudiant $Etudiant
     * @return Offre
     */
    public function setEtudiant($Etudiant)
    {
        $this->Etudiant = $Etudiant;
    }





    /**
     * Set session
     *
     * @param \SiteBundle\Entity\Session $session
     *
     * @return Offre
     */
    public function setSession(\SiteBundle\Entity\Session $session = null)
    {
        $this->Session = $session;

        return $this;
    }

    /**
     * Get session
     *
     * @return \SiteBundle\Entity\Session
     */
    public function getSession()
    {
        return $this->Session;
    }

    /**
     * Set typeContrat
     *
     * @param string $typeContrat
     *
     * @return Offre
     */
    public function setTypeContrat($typeContrat)
    {
        $this->typeContrat = $typeContrat;

        return $this;
    }

    /**
     * Get typeContrat
     *
     * @return string
     */
    public function getTypeContrat()
    {
        return $this->typeContrat;
    }

    /**
     * Set document
     *
     * @param string $document
     *
     * @return Offre
     */
    public function setDocument($document)
    {
        $this->document = $document;

        return $this;
    }

    /**
     * Get document
     *
     * @return string
     */
    public function getDocument()
    {
        return $this->document;
    }
}

src/SiteBundle/Resources/views/Entreprise/accueil_entreprise.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <div class="jumbotron">
        <h2> Bienvenue</h2>
        Vous êtes sur la page d'accueil des entreprises. Vous pouvez voir la liste de toutes vos offres d'alternance,
        les postulants. Vous pouvez ensuite gerer les demandes d'alternance. Si vous ne possédez pas encore d'offre vous
        pouvez en ajouter en appuyant sur le bouton : "Postez une Annonce".
        </br>
        <div class="text-center margTop10">
            <a class="btn btn-default " href="{{ path('site_ajoutAnnonce') }}">Postez une Annonce</a>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">
            <h3>Offres en Ligne</h3>
        </div>
        <div class="panel-body">
            {% for offre in offresLigne %}

                <h4>{{ offre.titre }}
                    <small><a href="{{ path('site_detailsAnnonceEntreprise', {'annonceId': offre.id }) }}"><span
                                    class="glyphicon glyphicon-search margR10"></span></a><a
                                href="{{ path('site_supprAnnonce', {'annonceId': offre.id }) }}"><span
                                    class="glyphicon glyphicon-trash"></span></a></small>
                </h4>

                <table class="table table-bordered">
                    <tr>
                        <th class="col-md-2">Nom Prenom</th>
                        <th class="col-md-2 text-center">Age</th>
                        <th class="col-md-2 text-center">CV</th>
                        <th class="col-md-2 text-center">Lettre De Motivation</th>
                        <th class="col-md-2 text-center">Profil</th>
                    </tr>
                    {% for postulants in postulantOffres %}


                        {% for postulant in postulants %}

                            {% if postulant.offre.id == offre.id and postulant.etat != "Refuser" %}

                                <tr>
                                    <td {% if postulant.etat=="Attente Etudiant" %} style="color:darkgreen" {% endif %}>{{ postulant.etudiant.laPersone.nom }} {{ postulant.etudiant.laPersone.prenom }}</td>
                                    <td class="text-center">{{ postulant.etudiant.getAge() }} ans</td>
                                    <td class="text-center"><a target="_blank"
                                                               href="{{ asset(postulant.etudiant.cv) }}"><span
                                                    class="glyphicon glyphicon-eye-open "></span></a></td>
                                    <td class="text-center"><a data-toggle="modal"
                                                               data-target="#LettreMotivation{{ postulant.offre.id }}"><span
                                                    class="glyphicon glyphicon-eye-open"></span></a></td>
                                    <td class="text-center"><a
                                                href="{{ path('site_detailsPostulant', {'postulantId': postulant.id }) }}"><span
                                                    class="glyphicon glyphicon-eye-open margR5"></span></a><a
                                                href="{{ path('site_impressionPostulant', {'postulantId': postulant.id }) }}"
                                                target="_blank"><span class="glyphicon glyphicon-print"></span></a></td>
                                    <!-- Modal lettre motivation -->
                                    <div id="LettreMotivation{{ postulant.offre.id }}" class="modal fade" role="dialog">
                                        <div class="modal-dialog">
                                            <!-- Modal content-->
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close"
                                                            data-dismiss="modal">&times;</button>
                                                    <h4>Lettre de motivation
                                                        de {{ postulant.etudiant.laPersone.nom }} {{ postulant.etudiant.laPersone.prenom }}</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>{{ postulant.lettreMotivation }}</p>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </tr>

                            {% elseif postulant.etat != "Refuser" %}
                                <tr>
                                    <td class="alert alert-warning" colspan="5">Aucun étudiant a postulé à cette offre.
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}

                    {% endfor %}
                </table>

            {% endfor %}

        </div>

    </div>

    <div class="panel panel-danger">
        <div class="panel-heading">
            <h3>Offre en attente de validation du responsable de la licence</h3>
        </div>
        <div class="panel-body">
            {% for offreV in offresValidations %}
                <h4>{{ offreV.titre }}
                    <small><a href="{{ path('edditAnnonceEntreprise', {'annonceId': offreV.id }) }}"><span
                                    class="glyphicon glyphicon-pencil margR5 "></span></a> <a
                                href="{{ path('site_detailsAnnonceEntreprise', {'annonceId': offreV.id }) }}"><span
                                    class="glyphicon glyphicon-search margR5"></span></a><a
                                href="{{ path('site_supprAnnonce', {'annonceId': offreV.id}) }}"><span
                                    class="glyphicon glyphicon-trash"></span></a></small>
                </h4>

            {% endfor %}
        </div>
    </div>
    <div class="panel panel-danger">
        <div class="panel-heading">
            <h3>Offre en attente de modification demander par le Responsable de la licence</h3>
        </div>
        <div class="panel-body">
            {% for offreM in offresModification %}
                <h4>{{ offreM.titre }}
                    <small><a href="{{ path('edditAnnonceEntreprise', {'annonceId': offreM.id }) }}"><span
                                    class="glyphicon glyphicon-pencil margR5 "></span></a> <a
                                href="{{ path('site_detailsAnnonceEntreprise', {'annonceId': offreM.id }) }}"><span
                                    class="glyphicon glyphicon-search margR5"></span></a><a
                                href="{{ path('site_supprAnnonce', {'annonceId': offreM.id}) }}"><span
                                    class="glyphicon glyphicon-trash"></span></a></small>
                </h4>

            {% endfor %}
        </div>
    </div>
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3>Offre Pourvue</h3></div>
        <div class="panel-body">
            {% for offreP in offresPourvues %}
                <h4>{{ offreP.titre }}
                    <small><a href="{{ path('site_detailsAnnonceEntreprise', {'annonceId': offreP.id }) }}"><span
                                    class="margR5 glyphicon glyphicon-search margR5"></span></a></small>
                </h4>
                <table class="table table-bordered">
                <tr>
                    <th class="col-md-2">Nom Prenom</th>
                    <th class="col-md-2 text-center">Age</th>
                    <th class="col-md-2 text-center">CV</th>
                    <th class="col-md-2 text-center">Etat du dossier d'inscription</th>
                    <th class="col-md-2 text-center">Profil</th>
                </tr>
                <tr>
                    <td>{{ offreP.etudiant.laPersone.nom }} {{ offreP.etudiant.laPersone.prenom }}</td>
                    <td class="text-center">{{ offreP.etudiant.getAge() }} ans</td>
                    <td class="text-center"><a target="_blank" href="{{ asset(offreP.etudiant.cv) }}"><span
                                    class="glyphicon glyphicon-eye-open "></span></a></td>

                    {% if offreP.etudiant.DossierInscription.etatDossier == '2' %}
                        <td><p class="text-danger">Pré-inscription du Contrat</p></td>

                    {% elseif offreP.etudiant.DossierInscription.etatDossier == '3' %}
                        <td><p class="text-info">Dossier inscription pédagogique</p></td>

                    {% elseif offreP.etudiant.DossierInscription.etatDossier == '4' %}
                        <td><p class="text-success">Signature du contrat</p></td>
                    {% elseif offreP.etudiant.DossierInscription.etatDossier == '5' %}
                        <td><p class="text-success">Inscription terminée</p></td>
                    {% elseif offreP.etudiant.DossierInscription.etatDossier == '-1' %}
                        <td><p class="text-success">Candidat refusé</p></td>
                    {% endif %}
                    <td class="text-center"><a
                                href="{{ path('site_detailsEtudiant', {'offreId': offreP.id }) }}"><span
                                    class="glyphicon glyphicon-eye-open margR5"></span></a></td>
                </tr>

                </table>{% endfor %}

        </div>
    </div>

{% endblock %}

src/SiteBundle/Resources/views/Entreprise/detailsEtudiant.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>Alternant pour l'offre {{ offre.titre }}</h1>
    <div>
        <p><label>Nom : </label> {{ offre.etudiant.laPersone.nom }}</p>
        <p><label>Prenom : </label> {{ offre.etudiant.laPersone.prenom }}</p>
        <p><label>Sexe : </label> {{ offre.etudiant.laPersone.sexe }}</p>
        <p><label>Email : </label> {{ offre.etudiant.laPersone.mail }}</p>
        <p><label>Téléphone : </label> {{ offre.etudiant.laPersone.telephone }}</p>
        <p><label>Adresse
                : </label> {{ offre.etudiant.laPersone.adresse.commune }} {{ offre.etudiant.laPersone.adresse.codePostal }}         </p>
        <p><label>CV : </label> <a target="_blank" href="{{ asset(offre.etudiant.cv) }}"><span
                        class="glyphicon glyphicon-eye-open"></span></a></p>

    </div>
    <div class="text-center">
        <a class="btn btn-primary" href="#"><span class="glyphicon glyphicon-envelope"></span> Contacter</a>
        <a class="btn btn-default" href="{{ path('site_accueilEntreprise') }}">Retour</a>
    </div>

{% endblock %}

src/SiteBundle/Resources/views/Entreprise/detailsPostulants.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>Postulant a l'offre {{ postulant.offre.titre }}</h1>
    <div>
        <p><label>Nom : </label> {{ postulant.etudiant.laPersone.nom }}</p>
        <p><label>Prenom : </label> {{ postulant.etudiant.laPersone.prenom }}</p>
        <p><label>Sexe : </label> {{ postulant.etudiant.laPersone.sexe }}</p>
        <p><label>Email : </label> {{ postulant.etudiant.laPersone.mail }}</p>
        <p><label>Téléphone : </label> {{ postulant.etudiant.laPersone.telephone }}</p>
        <p><label>Adresse
                : </label> {{ postulant.etudiant.laPersone.adresse.commune }} {{ postulant.etudiant.laPersone.adresse.codePostal }}
        </p>
        <p><label>CV : </label> <a target="_blank" href="{{ asset(postulant.etudiant.cv) }}"><span
                        class="glyphicon glyphicon-eye-open"></span></a></p>
        <p><label>Lettre de motivation : </label> {{ postulant.lettreMotivation }}</p>
    </div>
    <div class="text-center">
        <a class="btn btn-primary" href="#" style="display: none" ><span class="glyphicon glyphicon-envelope"></span> Contacter</a>
        <a class="btn btn-success" href="{{ path('site_accepterPostulant' , {'postulantId': postulant.id }) }}"><span class="glyphicon glyphicon-ok"></span> Acccepter</a>
        <a class="btn btn-danger" href="{{ path('site_refusPostulant',{'postulantId': postulant.id }) }}"><span class="glyphicon glyphicon-remove"></span> Refuser</a>
        <a class="btn btn-default" href="{{ path('site_accueilEntreprise') }}">Retour</a>
    </div>

{% endblock %}

src/SiteBundle/Resources/views/Entreprise/impressionPostulants.html.twig
{% extends '::baseImpression.html.twig' %}
{% block body %}
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <h1>Profil d'un étudiant</h1>
        </div>
        <div class="col-sm-3"></div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h2>Offre : {{ postulant.offre.titre }}</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <h1>Profil d'un étudiant</h1>
        </div>
        <div class="col-sm-3"></div>
    </div>
    <div>
        <p><label>Nom : </label> {{ postulant.etudiant.laPersone.nom }}</p>
        <p><label>Prenom : </label> {{ postulant.etudiant.laPersone.prenom }}</p>
        <p><label>Sexe : </label> {{ postulant.etudiant.laPersone.sexe }}</p>
        <p><label>Email : </label> {{ postulant.etudiant.laPersone.mail }}</p>
        <p><label>Téléphone : </label> {{ postulant.etudiant.laPersone.telephone }}</p>
        <p><label>Adresse
                : </label> {{ postulant.etudiant.laPersone.adresse.commune }} {{ postulant.etudiant.laPersone.adresse.codePostal }}
        </p>
        <p><label>Lettre de motivation : </label> {{ postulant.lettreMotivation }}</p>
    </div>
{% endblock %}

src/SiteBundle/Resources/views/Entreprise/inscription_entreprise.html.twig
{% extends '::base.html.twig' %}
{% form_theme form 'bootstrap_3_horizontal_layout.html.twig' %}
{% block title %}
    Inscription entreprise
{% endblock %}

{% block body %}
    <h1>Inscription entreprise</h1>
    {{ form(form) }}
{% endblock %}

src/SiteBundle/Resources/views/Entreprise/modification_entreprise.html.twig
{% extends 'base.html.twig' %}
{% block body %}
 {{  form(form) }}

{% endblock %}